### ISSUE TITLE
Multiple subscribers/consumers per queue

### ISSUE THREAD

**Issue by pnowy** [yoomoney/db-queue#29]
Hi,

I was looking into the project and was wondering is there a way to have multiple consumers/subscribers for single queue and single task?

I have in mind the case that I'm registering the task and have registered for the given queue 2 consumers in the same app and both receive/process enqueued task.

Thanks

**Comment by f0y** [comment]
Hi, db-queue doesn't have support for pub/sub model. I suggest you to register identical tasks with separate consumers and producers.

**Comment by pnowy** [comment]
Thx for the answer!
